
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yqmwjcnmzizpbnzixocf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlxbXdqY25teml6cGJueml4b2NmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI2MDU3MjgsImV4cCI6MjA1ODE4MTcyOH0.PdjC-EHuISENaRuhUgwHuh3mzDIBJXsBF3buZb6-zEI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// Create a redirect URL based on the current origin
const getRedirectUrl = () => {
  if (typeof window !== 'undefined') {
    return `${window.location.origin}/auth/callback`;
  }
  return 'http://localhost:3000/auth/callback';
};

export const supabase = createClient<Database>(
  SUPABASE_URL,
  SUPABASE_PUBLISHABLE_KEY,
  {
    auth: {
      autoRefreshToken: true,
      persistSession: true,
      detectSessionInUrl: true,
      flowType: 'pkce'
    }
  }
);
